[package]
name = "rdpcore-rdpeai-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rdpcore-rdpeai = { path = ".." }

[[bin]]
name = "decode_rdpeai"
path = "fuzz_targets/decode_rdpeai.rs"
test = false
doc = false
bench = false
