[package]
name = "rdpcore-dvc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rdpcore-dvc = { path = ".." }

[[bin]]
name = "decode_dvc"
path = "fuzz_targets/decode_dvc.rs"
test = false
doc = false
bench = false
